import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lets build Hulu 2.0</h1>
      <ul>
        <li>
          <Link href="/dashboard">Dashboard page</Link>
        </li>
        <li>
          <Link href="/users">Users page</Link>
        </li>
      </ul>
      <Header />
    </div>
  );
};

export default Home;
