import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CountriesTable from "../components/countriesTable";
import Header from "../components/header";

export default function Home() {
  return (
    <div className={styles["home-container"]}>
      <Head>
        <title>European Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CountriesTable />
    </div>
  );
}
