import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CountriesTable from "../components/countriesTable";
import Header from "../components/header";

export default function Home({ countriesList }) {
  return (
    <div className={styles["home-container"]}>
      <Head>
        <title>European Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CountriesTable countriesList={countriesList} />
    </div>
  );
}

export async function getStaticProps() {
  const response = await fetch(`https://restcountries.com/v3.1/region/europe`);
  const countriesList = await response.json();

  return {
    props: {
      countriesList,
    },
  };
}
